# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: employee-app
type: Opaque
stringData:  # Using stringData so we don't need to base64 encode
  username: "postgres"
  password: "your-secure-password"
  database: "employeedb"
